-- Create table to store cached equipment prices
create table public.equipment_prices (
  id bigint generated by default as identity primary key,
  make text not null,
  model text not null,
  data jsonb not null, -- Stores the list of scraper results
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Constraint to ensure unique Make/Model pairs
  unique(make, model)
);

-- Index for fast lookup
create index idx_equipment_make_model on public.equipment_prices(make, model);
